package MiniDOT.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Attribute_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.attributeId$_319));
    tgs.append("=");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.value$ltar));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink attributeId$_319 = MetaAdapterFactory.getContainmentLink(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda1480dL, 0x53ff9463eda14814L, "attributeId");
    /*package*/ static final SContainmentLink value$ltar = MetaAdapterFactory.getContainmentLink(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda1480dL, 0x53ff9463eda14d6fL, "value");
  }
}
