package MiniDOT.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Edge_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.sourceId$_3Z9));
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.targetIds$uEEs)) {
      tgs.appendNode(item);
    }
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.attributes$$WWF) != null)) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.attributes$$WWF));
    }

  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink sourceId$_3Z9 = MetaAdapterFactory.getContainmentLink(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda14807L, 0x53ff9463eda14819L, "sourceId");
    /*package*/ static final SContainmentLink targetIds$uEEs = MetaAdapterFactory.getContainmentLink(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda14807L, 0x53ff9463eda17b17L, "targetIds");
    /*package*/ static final SContainmentLink attributes$$WWF = MetaAdapterFactory.getContainmentLink(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda14807L, 0x53ff9463eda14810L, "attributes");
  }
}
