package MiniDOT.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ID_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.ID$$XTe));
  }

  private static final class PROPS {
    /*package*/ static final SProperty ID$$XTe = MetaAdapterFactory.getProperty(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda14812L, 0x53ff9463eda14813L, "ID");
  }
}
