package MiniDOT.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Node_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.nodeId$_32A));
    if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.attributes$$Xbd) != null)) {
      tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.attributes$$Xbd));
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink nodeId$_32A = MetaAdapterFactory.getContainmentLink(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda14806L, 0x53ff9463eda14815L, "nodeId");
    /*package*/ static final SContainmentLink attributes$$Xbd = MetaAdapterFactory.getContainmentLink(0x19ed932bf9694b45L, 0x993fc50c3cc8fe5cL, 0x53ff9463eda14806L, 0x53ff9463eda14811L, "attributes");
  }
}
